<?php

namespace PlanningBundle\Repository;

/**
 * PlanningAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningAgentRepository extends \Doctrine\ORM\EntityRepository
{
    public function hasDomaine($id_domaine, $id_agent){

	$exist = $this->_em->createQuery('SELECT pu.id
   		FROM PlanningBundle:PlanningAgent pu
        	WHERE pu.idAgent = :id_agent AND pu.idDomaine = :domaine')
            ->setParameters(array(
            	    'id_agent' => $id_agent,
		    'domaine' => $id_domaine[0]['id']
        	))
            ->getResult();
        if (empty($exist))
            return 0;
        else
            return 1;
    }

    public function isDispo($id_agent, $date){
	$exist = $this->_em->createQuery('SELECT p.id
   		FROM PlanningBundle:Planning p
        	WHERE p.idAgent = :id_agent AND p.heureDebut = :startDate')
            ->setParameters(array(
            	    'id_agent' => $id_agent,
		    'startDate' => $date
        	))
            ->getResult();
        if (empty($exist))
            return 1;
        else
            return 0;
    }
}
