SELECT TITRE AS `titre`, DATE_DEBUT_AFFICHE AS `date_debut_affiche`, DATE_FIN_AFFICHE AS `date_fin_affiche`, (DATEDIFF(DATE_FIN_AFFICHE, DATE_DEBUT_AFFICHE) * 24) AS `temps_affiche`
FROM film
WHERE DATE_DEBUT_AFFICHE != 0000-00-00 AND DATE_FIN_AFFICHE != 0000-00-00;