-- MySQL Script generated by MySQL Workbench
-- 09/14/16 11:38:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema im
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema im
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `im` DEFAULT CHARACTER SET utf8 ;
USE `im` ;

-- -----------------------------------------------------
-- Table `im`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `im`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `CodePostal` VARCHAR(45) NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `EMAIL` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `im`.`Domaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `im`.`Domaine` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `NomDomaine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `im`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `im`.`Agent` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `IdDomaine` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_domaine_idx` (`IdDomaine` ASC),
  CONSTRAINT `fk_domaine_agent`
    FOREIGN KEY (`IdDomaine`)
    REFERENCES `im`.`Domaine` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `im`.`FicheIntervention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `im`.`FicheIntervention` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NULL,
  `IdDomaine` INT NULL,
  `Habitation` VARCHAR(45) NOT NULL,
  `Rapport` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_domaine_idx` (`IdDomaine` ASC),
  INDEX `fk_user_idx` (`IdUser` ASC),
  CONSTRAINT `fk_domaine`
    FOREIGN KEY (`IdDomaine`)
    REFERENCES `im`.`Domaine` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`IdUser`)
    REFERENCES `im`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `im`.`Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `im`.`Planning` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `HeureDebut` TIMESTAMP(6) NULL,
  `HeureFin` TIMESTAMP(6) NULL,
  `IdAgent` INT NULL,
  `IdFiche` INT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UNIQUE` (`HeureDebut` ASC, `HeureFin` ASC, `IdAgent` ASC),
  INDEX `fk_agent_idx` (`IdAgent` ASC),
  INDEX `fk_fiche_idx` (`IdFiche` ASC),
  CONSTRAINT `fk_agent`
    FOREIGN KEY (`IdAgent`)
    REFERENCES `im`.`Agent` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fiche`
    FOREIGN KEY (`IdFiche`)
    REFERENCES `im`.`FicheIntervention` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
