# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "deimosfr/debian-jessie"

  config.vm.network "forwarded_port", guest: 80, host: 8082

  config.vm.network "private_network", ip: "192.168.1.2"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"
    chef.roles_path = "../chef-repo/roles"
    chef.add_recipe "nginx"
    chef.add_role("balance")
    chef.add_recipe "default-route"
  end
end
