<?php

namespace PlanningBundle\Repository;

/**
 * FicheInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheInterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHeure($idFiche)
    {
        $sql = 'SELECT p.heureDebut
        FROM PlanningBundle:Planning p
        WHERE p.idFiche = :fiche';
        $heure = $this->_em->createQuery($sql)
            ->setParameters(array(
                'fiche' => $idFiche
            ))->getResult();
        if (empty($heure))
            return NULL;
        else
            return $heure;
    }
}
