<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Check if Email is on the BDD, if is return 1 else return 0
     * @param $email
     * @return int
     */
    public function findIsEmailExist($email)
    {
        $exist = $this->_em->createQuery('SELECT u.email
        FROM  UserBundle:User u
        WHERE u.email = :email')
            ->setParameter('email', $email)
            ->getResult();
        if (empty($exist))
            return 0;
        else
            return 1;
    }
}
