<?php

namespace PlanningBundle\Repository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * Return Id Domain for a name domain
     *
     * @param $domaine
     * @return array|null
     */

    public function findByNom($domaine)
    {
	$sql = 'SELECT d.id
        FROM PlanningBundle:Domaine d
        WHERE d.nomDomaine = :domaine';
        $id = $this->_em->createQuery($sql)
            ->setParameters(array(
                'domaine' => $domaine
            ))->getResult();
        if (empty($id))
            return NULL;
        else
            return $id;
    }
}
